### ISSUE TITLE
Display hit charges

### ISSUE THREAD

**Issue by harry-wood** [transportapi/api-console#10]
We need to indicate how many hits we charge for different endpoints in the new raml docs.

In the old docs that's currently displayed very prominently in titles (maybe a bit more prominent than it needs to be)

I'm also noticing there's a reference to this in the [terms and conditions](http://www.transportapi.com/terms/) including a link to the old docs.

> Note that not all endpoints are charged at 1 hit per request: see the Documentation at https://developer.transportapi.com/documentation for details. For example, public journey plans are charged at 10 hits per request for commercial users and 1 hit per request for UK Council Traveline members

**Comment by harry-wood** [comment]
I think it would probably be ok to just write something in the top description section of each endpoint (in the RAML) 

Appearing before the description? Keep it brief like this?:

"_**(10 hits)**_"

**Comment by mgogov** [comment]
Good spot.

The best thing would be to fetch those values straight [from the configuration](https://github.com/transportapi/main/blob/555b30f8c10df8162152f23960db2f67692d34e6/transportapi/transportapiv3/lib/util/threescale/methods.rb#L55-L95) and put them in the RAML automatically via ERBing the RAML files and doing some preprocessing.. but that's a longer story.

We should do it as a manual one off thing for now.

**Comment by harry-wood** [comment]
So if I sprinkle a bit of bold and italic, it'll look like this:
![screen shot 2016-08-25 at 17 51 25](https://cloud.githubusercontent.com/assets/227525/17978183/bc4f4d1c-6aec-11e6-9bab-e2cf92336bb2.png)

Any objections before I go ahead with this (rather tedious) task of copying hit charge details into raml files? Initially maybe I can make it less tedious by just doing the ones which are something other than "(1 hit)"

**Comment by madwort** [comment]
You could add "(1 hit)" to everything with a regex before you start?

**Comment by harry-wood** [comment]
yep can do. OK going ahead with this then
